### ISSUE TITLE
Firebase Authentication Module

### ISSUE THREAD

**Issue by franhenke** [franhenke/capstone-project-logbook#14]
### Value statement
-----
As a developer
I need a way to let users create an User Accout and to later store data in a database 
so that they will be able to create/edit and delete JournalEntries
and protect them within their account

### Description 
---

App will be registered and connected with firebase 
App will be hosted with firebase

### Acceptance criteria  
---

- [x] Keys are hidden in .env file

- [x] Keys are working

### Task
---

- [x] create new firebase project

- [x] set up Firebase Authentication Module

- [x] create .env-example, .env  and config.js and save the keys  

- [x] create handler in index.js

- [x] install firebase web

### size 
---
medium
