### ISSUE TITLE
Register / Login

### ISSUE THREAD

**Issue by franhenke** [franhenke/capstone-project-logbook#15]
### Value statement
-----
As a User
I need a way to create an account
to write my journal entries in a closed enviroment

### Description (Text, Scribble, Wireframe, Design)
---

<img width="474" alt="Bildschirmfoto 2020-07-23 um 15 00 09" src="https://user-images.githubusercontent.com/65188676/88289226-349d4f80-ccf5-11ea-8cb6-44f335791415.png">

Register and LoginPage in the same design // Design to be dark or light - will decide after seeing end result

User will be automatically redirected to "home" after registering/logging in successfully  

### Acceptance criteria  
---

- [x] User will be directed to Login page when opening the app for the first time

- [x] User can choose between Login or creating a new account

- [x] "Sign Up" will be recognizable as CTA link

- [x] Sign Up Link will direct to Register Form 

- [x] User will be redirected automatically after Login in or Sign Up

- [x] User can log in with their chosen user name/email and password

- [x] User won´t be able to visit app without registering first

- [x] New user date will be forwarded and stored on firebase

### Task
---

- [x] create Register.js

- [x] create Register form 

- [x] useRef to read the user data 

- [x] onSubmit event to forward form values

- [x] import to App.js

- [x] Routing

### size
---
large
