### ISSUE TITLE
Add JournalEntries to Firebase DB

### ISSUE THREAD

**Issue by franhenke** [franhenke/capstone-project-logbook#17]
### Value statement
---
As an app user,
I need a way to save my JournalEntries to a database
for the case that I change devices

### Description (Text, Scribble, Wireframe, Design)
---
JournalEntries will be added to the Database "journalentries" when the form is submitted

### Acceptance criteria
---

- [x]  JournalEntries will be added to the database "journalentries" after the JournalForm was subitted

- [x] Entries will be saved under the User's ID

- [x] Entries will still be saved in localstorage

### Tasks
---

- [x] Add Firestore to the project
- [x] create an onClick event onSubmit
- [x] insert event into the JournalForm
- [x] check in firebase console that the entries were successfully submitted 

### size
---
medium
