### ISSUE TITLE
Read Data from Firebase DB

### ISSUE THREAD

**Issue by franhenke** [franhenke/capstone-project-logbook#18]
### Value statement
----

As a developer,
I need a way to provide a way to provide the user with their data which was stored in the database
so they can have access to it when needed

### Description (Text, Scribble, Wireframe, Design)
JournalEntries will be read from the Database "journalentries" when the user is connected with its account and when the data in the localstorage is not complete and needs to be updated

### Acceptance criteria
 ---
- [x] JournalEntries will be received from the database when the user's localstorage and the database aren't matching

- [x] Entries from the database will be stored in the localstorage

### Tasks
---
 
- [x] add function to receive the data from the firestore

- [x] add possibility to check if the user's data in localstorage matches that of the database

- [x] read data and show on user's device

- [x] save received data in localstorage

### size

- [x] large
