### ISSUE TITLE
Modal / Successful input

### ISSUE THREAD

**Issue by franhenke** [franhenke/capstone-project-logbook#2]
### Value statement
---
As an App user,
I need an alert that my input was submitted
so that I can be sure that my journal entry was successful or not

### Description (Text, Scribble, Wireframe, Design)

- a modal pop up that is letting me know that my input was submitted successfully
- using Toastify

<img width="296" alt="Bildschirmfoto 2020-07-05 um 20 00 49" src="https://user-images.githubusercontent.com/65188676/86539079-3cd64c00-befa-11ea-9335-98236018e4c1.png">

### Acceptance criteria
---

 - [ ] colors and design match the rest of the app

- [ ] message shows that the entry was made successfully 

- [ ] message shows up that the Journal entry was added to the bookmarks

### Tasks
---
- [x] installing Toastify  

- [x] creating two different alerts : Journal Form submit & Add to Bookmarks

### Size
---
small
