### ISSUE TITLE
Datepicker

### ISSUE THREAD

**Issue by franhenke** [franhenke/capstone-project-logbook#3]
### Value statement
---
as an **App User**
I need to **select a Date** from within the JournalForm
to **keep** the **schema** of the date **consistent 

### Description (Text, Scribble, Wireframe, Design)
---
The input field should expand on click and reveal a datepicker

<img width="322" alt="Bildschirmfoto 2020-07-06 um 15 35 19" src="https://user-images.githubusercontent.com/65188676/86598994-4e712f80-bf9e-11ea-8c17-dbd96f76382e.png">

### Acceptance criteria
---

- [x] Datepicker is added to the JournalForm-component

- [x] Calender shows the current month

- [x] datepicker has a range of 7 days into the past

- [x] Calender and input field have the same styling as the rest of the App

- [x] Chose date is displayed in the format dd/mm/yyyy 

### Tasks
---

- [x] add datepicker library

- [x] create Datepicker.js

- [x] add to JournalForm as an input

- [x] check styling in Storybook

- [x] Write component test

- [x] Add to App.js

- [x] Add missing styles
