### ISSUE TITLE
Welcome Page

### ISSUE THREAD

**Issue by franhenke** [franhenke/capstone-project-logbook#6]
### Value statement
---
as a developer
I need to add a welcome page
to implement a log-in at a later stage

### Description (Text, Scribble, Wireframe, Design)
---
<img width="253" alt="Bildschirmfoto 2020-07-12 um 21 01 17" src="https://user-images.githubusercontent.com/65188676/87254422-d796d380-c482-11ea-9a44-bdf8fa40f335.png">

<img width="266" alt="Bildschirmfoto 2020-07-12 um 21 09 58" src="https://user-images.githubusercontent.com/65188676/87254620-0e211e00-c484-11ea-94cb-0ce671af985e.png">

Screen will welcome the user and prove a CTA button 

### Acceptance criteria
---

- [x] high contrast between the background image and the text

- [x] Icon as a button

- [x] button is clickable

### Tasks

- [x] create Welcome.js, Welcome.stories.js

- [x] create component

- [x] check style in storybook

- [x] add to App.js

- [x] add final styling

### size
---
small
